src/app/_partials/info/info.component.html
src/app/app.component.html
src/app/app.component.ts
src/app/pages/pet/pet.component.html
src/app/pages/pet/pet.component.ts

1. footer element added to app.component.html
2. pet tool tables aligned with 'flex align items'

footer added

---

.gitignore
src/app/_partials/header-top/header-top.component.html
src/app/_partials/log-in-tpl/log-in-tpl.component.html
src/app/_partials/log-in-tpl/log-in-tpl.component.spec.ts
src/app/_partials/log-in-tpl/log-in-tpl.component.ts
src/app/app.routes.ts
src/styles.scss

1. new component created under partials- log in tpl
2. log in form created and styled
3. log in background styled with gradient
4. router link added for log in page

Login page

---

src/app/_partials/footer/footer.component.html
src/app/_partials/info/info.component.html
src/app/_partials/info/info.component.ts
src/app/_partials/log-in-tpl/log-in-tpl.component.html
src/app/_partials/log-in-tpl/log-in-tpl.component.ts
src/app/_partials/registration-form-tpl/registration-form-tpl.component.html
src/app/_partials/registration-form-tpl/registration-form-tpl.component.spec.ts
src/app/_partials/registration-form-tpl/registration-form-tpl.component.ts
src/app/app.routes.ts
src/app/pages/registration-form/registration-form.component.html
src/app/pages/registration-form/registration-form.component.spec.ts
src/app/pages/registration-form/registration-form.component.ts
src/styles.scss

1. new components created - registration form template and registration form page
2. registration form displayed in two p-panels  and styled 
3. input fields have ng models 
4. input fields changed with suitable form components

Register form

---

src/app/_partials/msx-tpl/msx-tpl.component.html
src/app/_partials/msx-tpl/msx-tpl.component.spec.ts
src/app/_partials/msx-tpl/msx-tpl.component.ts
src/app/app.routes.ts
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/local-decarbonisation/local-decarbonisation.component.html
src/styles.scss

1. dashboard created and styled
2. envirotracks displayed in a p-card instead of p-panel
3. side menu - envirotrack reports displayed with p-panelMenu component
4. local decarbonisation - content added for the 2 councils

Dashboard menu fix

---

src/app/_partials/local-decab-single-tpl/local-decab-single-tpl.component.html
src/app/_partials/msx-tpl/msx-tpl.component.html
src/app/app.routes.ts
src/app/pages/local-decarbonisation/local-decarbonisation.component.html

1. content changed and added to derry & msw pages
2. responsive col & order classes for local decab pages
3. font style classes
4. local decab multi page, content placed in a div container

Local decab pages

---

src/app/_partials/home-technology-tpl/home-technology-tpl.component.html
src/app/_partials/home-technology-tpl/home-technology-tpl.component.ts
src/app/_partials/local-decab-single-tpl/local-decab-single-tpl.component.html
src/app/_partials/local-decab-single-tpl/local-decab-single-tpl.component.ts
src/app/_partials/msx-tpl/msx-tpl.component.html
src/app/_partials/msx-tpl/msx-tpl.component.ts
src/app/_partials/news-cards-tpl/news-cards-tpl.component.html
src/app/_partials/news-cards-tpl/news-cards-tpl.component.ts
src/app/pages/landing-page/landing-page.component.html
src/app/pages/landing-page/landing-page.component.ts

1. home section - latest technology - information displayed in a carousel using the database
2. news card tpl- populated with 'content.item' & for loop created for each card
3. padding & margin added to home section - latest technologies

Home page content

---

src/app/pages/landing-page/landing-page.component.html

1. carousel for home new technologies

home-latest-technologies carousel added

---

src/app/pages/events/events.component.html

1. position changed to img and content and everything is aligned

positions changed to img and text

---

src/app/_partials/event-cards-tpl/event-cards-tpl.component.html
src/app/_partials/local-decab-single-tpl/local-decab-single-tpl.component.html
src/app/_partials/local-decab-single-tpl/local-decab-single-tpl.component.ts
src/app/_partials/top-page-img-tpl/top-page-img-tpl.component.html
src/app/pages/events/events.component.html
src/app/pages/events/events.component.ts
src/app/pages/local-decarbonisation/local-decarbonisation.component.html
src/app/pages/local-decarbonisation/local-decarbonisation.component.ts
src/assets/img/curve-grey.svg
src/styles.scss

1. top image added from the db and api call was made
2. news page - cards were styled with extra margin, height was added, content was added to cards
3. local decab single html - new layout created 
4.

Factsheet tpl

---

src/app/_partials/header-top/header-top.component.ts
src/app/app.routes.ts
src/app/pages/advisory-board/advisory-board.component.html
src/app/pages/advisory-board/advisory-board.component.spec.ts
src/app/pages/advisory-board/advisory-board.component.ts
src/app/pages/partners/partners-content-tpl/partners-content-tpl.component.html
src/app/pages/partners/partners-content-tpl/partners-content-tpl.component.spec.ts
src/app/pages/partners/partners-content-tpl/partners-content-tpl.component.ts
src/app/pages/partners/partners.component.html
src/app/pages/partners/partners.component.spec.ts
src/app/pages/partners/partners.component.ts
src/app/pages/partners/single-partner/single-partner.component.html
src/app/pages/partners/single-partner/single-partner.component.spec.ts
src/app/pages/partners/single-partner/single-partner.component.ts
src/app/pages/project-information/project-information.component.html
src/app/pages/project-information/project-information.component.spec.ts
src/app/pages/project-information/project-information.component.ts
src/styles.scss

1. new components created - project info, partners,partners content,single partner and advisory board
2. api calls drom db were made to the new components
3. the new components have route links

Project info

---

package.json
src/app/pages/pet/pet.component.html
src/app/pages/pet/pet.component.scss
src/app/pages/pet/pet.component.ts
yarn.lock

Added new version of pet tool.
Calculates the percentile from a spreadsheet

Improved PET tool

---

src/app/_partials/footer/footer.component.ts
src/app/_partials/header-top/header-top.component.ts
src/app/app.routes.ts
src/app/pages/events/events.component.html
src/app/pages/events/events.component.ts
src/app/pages/virtual-tour/virtual-tour.component.html
src/app/pages/virtual-tour/virtual-tour.component.spec.ts
src/app/pages/virtual-tour/virtual-tour.component.ts
src/styles.scss

1. new component created - virtual tour page
2. api call and router link made for virtual page
3. videos added in a grid with cards
4. events page - past events - 'link added' and @if to the button

Virtual tour

---

src/app/app.routes.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/data-privacy/data-privacy.component.html
src/app/pages/data-privacy/data-privacy.component.spec.ts
src/app/pages/data-privacy/data-privacy.component.ts
src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet/pet.component.html
src/app/users/register/register.component.html
src/app/users/register/registration-form/registration-form.component.html
src/app/users/register/registration-form/registration-form.component.ts

1. data privacy component created
2. pet tool paragraph added

Import files

---

src/app/users/register/register.component.html
src/app/users/register/register.component.ts

1. @ if statement in registration changed to policy_idni, policy and policy_bill
2. registration ts file - validation if statements changed when to display the password

if statement changed and validations changed

---

src/app/_partials/header-top/header-top.component.ts
src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts

1. Pet tool (log in) - dropdown option added under Cost of Raw Materials
2. Pet tool (log in) - dropdown has width 
3. Pet tool (log in) - @if() added to display the dropdown
4. Pet tool (log in) - section class removed and text was placed in a container
5. NavBar - 'advisory board' removed and 'lates tech' changed to 'green tech'

Pet tool dropdown

---

src/app/_partials/header-top/header-top.component.html
src/app/app.routes.ts
src/app/pages/pet/pet.component.html
src/app/pages/pet/pet.component.ts

- Removed login button from nav and routes
- Added Chart and productivity percentile to the free pet table.

Removed Login button/PET tool chart added

---

src/app/_partials/local-decab-single-tpl/local-decab-single-tpl.component.html

1. local decarb single page - div added with title and paragraph under the img

local decab single - new paragraph was added with heading and paragraph

---

src/app/users/register/register.component.html

1. p-card component changed with div - pet card
2. labels and checkboxes displayed in a flex
3. p-inputGroupAddon style added

Register page style

---

src/app/users/register/register.component.html

comment deleted

---

src/app/_services/users/auth.service.ts
src/app/app.routes.ts
src/app/pages/envirotrack/envirotrack.service.ts
src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.ts
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.html
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.ts
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.ts
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.ts
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.html
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.ts
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.html
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.ts
src/app/pages/envirotrack/report/type-chart/type-chart.component.html
src/app/pages/envirotrack/report/type-chart/type-chart.component.ts
src/app/users/forgot-password/forgot-password.component.html
src/app/users/forgot-password/forgot-password.component.ts
src/app/users/login/login.component.html
src/app/users/login/login.component.ts

Assorted bug fixes from #64
Outstanding Bugs: 
- Forgot Password button doesn’t do anything
- Emailer not working - CORS error on post
- Heatmap - mpan number disappearing after it was disselected and selected again

Bug Fixes 

---

src/app/app.component.html
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.html
src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.ts
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.html
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.ts
src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.html
src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.ts
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.html
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.ts
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.html
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.ts
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.html
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.html
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.html
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.ts
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.html
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.ts
src/app/pages/envirotrack/report/type-chart/type-chart.component.html
src/app/pages/envirotrack/report/type-chart/type-chart.component.ts

1. information text was added on chart, data upload and fuel data
2. pet-cards added to charts

Dashboard information text

---

src/app/_helpers/http-interceptor.service.ts
src/app/_services/db.service.ts
src/app/_services/global.service.ts
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.scss
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/envirotrack/envirotrack.service.ts
src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.ts
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.html
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.ts
src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.ts
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.html
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.ts
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.ts
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.ts
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.ts
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.html
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.ts
src/app/pages/envirotrack/report/type-chart/type-chart.component.html
src/app/pages/envirotrack/report/type-chart/type-chart.component.ts
src/app/pages/help/bug-report/bug-report.component.ts
src/app/pages/pet-login-protected/pet-login-protected.component.ts
src/app/pages/reports/generate-report/generate-report.component.ts
src/app/users/login/login.component.html

1. Pressing enter on password input now submits login()
2. Http interceptor
3. adding level 2 consultant level
4. Adding consultant permissions to all dropdowns
5. fixing scope chart
6. Added return if no data provided
7. Fixing type chart data to not change everytime the company is clicked.
8. Uploaded data now attaches to the correct company, 1-3 files allowed
9. Added a trycatch block to prevent logout
10. Fixed the issue if the user uploads CSV data
11. Adding company name to email template

Quick fixes 14 05

---

src/app/pages/dashboard/dashboard.component.html
src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.html
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.html
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.html
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.html
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.ts
src/app/pages/envirotrack/report/type-chart/type-chart.component.html
src/app/pages/envirotrack/report/type-chart/type-chart.component.ts
src/app/pages/help/bug-report/bug-report.component.html
src/app/pages/help/faqs/faqs.component.html
src/app/pages/help/faqs/faqs.component.ts
src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/reports/generate-report/generate-report.component.html
src/styles.scss

1. import envirotrack - content placed in a p-card, width size added
2. fuel data - content wrapped in p-card, width size added
3. pet tool - pcard wrapps the content
4. recommendation - pcard wrapps the content
5. type chart - radius expanded to 180
6. scope chart - if() changed, showChart replaced with chartOptions
7. scope chart - radius expanded to 180
8. scope chart - fixing chart showing when no data available
9. bug report & faqs - wrapped in section and p-card
10. sidenav - width size changed and responsive width added

Dashboard items position

---

src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.html
src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.html
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.html
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.html
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.ts
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.html
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.html
src/app/pages/envirotrack/report/type-chart/type-chart.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/reports/generate-report/generate-report.component.html
src/styles.scss

1. @if() changed on charts
2. user level - company name is visible as selected button

User selected company

---

src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.ts
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.ts
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.ts
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.ts

1. envirotracks - filterData () - this.month.length+1
2. all charts are displaying the last day of the month

Envirotrack last day display

---

src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.ts
src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts

1. new chart added to pet tool log in - gauge chart
2. initChartGauge() added to filter the data
3. charts positioned in a grid and if() statement
4. responsive chart size added
5. reposnsive col size added

Pet tool gauge chart

---

src/app/pages/pet-login-protected/pet-login-protected.component.html

Richards requests for the PET tool
- More Steel types added
- Moved staff commute into Company travel
- Allow users to add their own material types
- Added ASC data upload
- ASC now shows on demand chart

PET Updates

---

src/app/pages/help/bug-report/bug-report.component.ts
src/app/pages/help/bug-report/bug-report.liquid

1. new file added to bug report folder - bug-report.liquid
2. email tpl was styled
3. svg img was added to the tpl
4. tested and it is working

bug-report email tpl created

---

src/app/_services/global.service.ts

Added try catch statement to global.service.ts in the Storage class for the getter

Fixed login

---

src/app/_services/users/auth.service.ts
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.ts

1. log out btn added on the side menu and sidebar menu
2. logout() was created on auth.services,using async, await and refresh token
3. auth service - logout() - route navigate path changed to login
4. dashboard - handleLogOut() created to complete the log out and to display message

105 log out button

---

src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.html
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.ts

Implementing fixes to the christmas day chart, removing excess years from select buttons,
default to the latest year

Christmas Day chart fixes

---

src/app/pages/dashboard/dashboard.component.ts

104-company-user-profile

---

src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts
src/app/pages/pet-login-protected/pet-tool-types.ts

1. pet tool - annual output option
2. custom unit types added to annual output option
3. pet tool - introduction text changed

111 updating pet text and adding total production

---

src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.ts
src/app/users/account/company-profile/company-profile.component.html
src/app/users/account/user-profile/user-profile.component.html
src/app/users/forgot-password/password-reset.liquid
src/styles.scss

1. dashboard menu items moved in different order
2. user profile and company profile are responsive
3. new menu link for account
4. sidenav - menu links ordered 
5. password liquid link updated

110 ordering menu links

---

src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts
src/app/pages/pet-login-protected/pet-tool-classes.ts
src/app/pages/pet-login-protected/pet-tool-types.ts
src/app/pages/reports/generate-report/generate-report.component.html
src/app/pages/reports/generate-report/generate-report.component.ts
src/app/pages/reports/generate-report/recommendations.ts

1. recommendation - exportExcel () added
2. Adding functionality to calculate co2e
3. recommendationCol array created
4. recommendations are mapped so we can get the rows we need
5. excel file name changed to "Recommendation Summary"
6. total functions created
7. totalRows added to display the total number on the same row
8. Data Analysis table added - data integrated
9. data analysis has export function
10. data analysis moved in p-tabview panel, header added and p-panel deleted

114 nersis requests

---

src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts
src/app/pages/pet-login-protected/pet-tool-types.ts

- Added Metres to UOM in Materials
- Added 2 decimal places to most inputs
- Cost of Raw Materials now calculates units * cost added to total
- Staff commute moved back to its own row.

Fixes 10/06/24

---

src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts

1. two pie charts are created for pet tool
2. Dropdown now triggers charts
3. if() is wrapping the p-cards for pie charts
4. conversion factors added for natural gas off grid,bio gas off grid, biomass,coal
5. Charts should show on initial database fetch now.
6. Fixed issue with cost of raw materials showing
7. Added cost of raw materials calculation back in
8. Energy cost should show now
9. Annual Output units dropdown should avoid duplicate options
10. console.log removed

Co2e charts pet tool

---

src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/sidebar-menu/sidebar-menu.component.html
src/app/pages/dashboard/sidebar-menu/sidebar-menu.component.spec.ts
src/app/pages/dashboard/sidebar-menu/sidebar-menu.component.ts
src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.ts
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.html
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.ts
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.html
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.ts
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.html
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.ts
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.html
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.ts
src/app/pages/help/bug-report/bug-report.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/reports/generate-report/generate-report.component.html
src/app/users/account/company-profile/company-profile.component.html
src/app/users/account/user-profile/user-profile.component.html
src/styles.scss

1. sidebar span dropdowns have cursor pointer
2. new component created under dashboard
3. mpans changed to dropdowns
4. dashboard - changed from flex to grid
5. container class removed from company profile and user profile
6. responsive classes added to dashboard, pet tool, sidebar
7. bug report form size fixed
8. pet tool overflow x added to p-card
9. scatter,bar, xmas chart - dates were formatted

117 responsive screen size

---

src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.ts

Fixing asc chart line on demand chart

118 maximum demand chart asc line

---

src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts

1. co2eBreakdown chart data from hhd and non hh data sources
2. co2eScope chart data from hhd and non hh data sources
3. conversion factors added for oil and biofuels
4. pie charts fixed to display correctly hhd and non half hourly data
5. console.log and comments deleted

125 pet tool pie charts

---

src/app/app.routes.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/sidebar-menu/sidebar-menu.component.html
src/app/pages/envirotrack/import/data-capture-import-spreadsheet/data-capture-import-spreadsheet.component.html
src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.ts
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.html
src/app/pages/envirotrack/report/envirotrack-report-fields/envirotrack-report-fields.component.html
src/app/pages/envirotrack/report/envirotrack-report-fields/envirotrack-report-fields.component.spec.ts
src/app/pages/envirotrack/report/envirotrack-report-fields/envirotrack-report-fields.component.ts
src/app/pages/reports/generate-report/generate-report.component.html
src/app/pages/reports/generate-report/generate-report.component.ts

Adding the fuel usage chart to IDNI

Adding fuel usage chart

---

src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts

1. chartX, chartY, testChart were added to onSelectCompany()

heatmap - onSelectCompany() - chartX, chartY,testChart added

---

src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.html
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.html
src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.html
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.html
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.html
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.ts
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.html
src/app/pages/envirotrack/report/envirotrack-report-fields/envirotrack-report-fields.component.html
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.html
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.html
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.ts
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.html
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.html
src/app/pages/envirotrack/report/type-chart/type-chart.component.html
src/app/pages/envirotrack/report/type-chart/type-chart.component.ts
src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts
src/app/pages/reports/generate-report/generate-report.component.html
src/app/pages/reports/generate-report/generate-report.component.ts

1. if statement for user deleted and dropdown added istead of select button
2. search filter added on dropdown component
3. pet tool - getCompanies() - "id" added to function
4. type chart - select company dropdown fixed
5. small pie chart - selectedCompany is number, selectCompany() adjusted
6. pie chart - if() filteredData.length was added to hide the console log error
7. pie chart - chartOptions & chartData are added to onSelectCompany()
8. bar chart - selectedCompany is number and ngInit () adjusted
9. xmax chart- chartOptions & mpan & defaultFilters added to onSelectCompany
10. heatmap - testChart and mpan added to onSelectCompany()
11. fuel usage chart-placed in a section & p-card, padding added to buttons
12. report- recommendations,typeTotals,scopeTable and totalConsumption were …

131 select company

---

src/app/pages/envirotrack/import/supply/supply.component.html
src/app/pages/envirotrack/import/supply/supply.component.ts
src/app/pages/envirotrack/report/envirotrack-report-fields/envirotrack-report-fields.component.html
src/app/pages/envirotrack/report/envirotrack-report-fields/envirotrack-report-fields.component.ts
src/styles.scss

1. sidebar was added to fuel usage chart
2. sidebar was added to supply component

137 description

---

src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.html
src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.ts

- Allowing emails to send more than 1 file
- Updated email subject line
- envirotrack upload now resets the company

Fixing mailer/envirotrack data upload

---

src/app/pages/reports/generate-report/generate-report.component.html

Download button on the recommendation table page.

Adding download button for report

---

src/app/pages/envirotrack/envirotrack.service.ts
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.html
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.ts
src/app/pages/envirotrack/report/type-chart/type-chart.component.html
src/app/pages/envirotrack/report/type-chart/type-chart.component.ts
src/app/pages/pet-login-protected/pet-login-protected.component.html
src/app/pages/pet-login-protected/pet-login-protected.component.ts

Updated the HTML and TypeScript files of scope and type chart components to improve structure and logic. Enhanced the company selection process and integrated the dbService for data retrieval, allowing dynamic updates based on selected company.

Refactor chart components and integrate company selection logic

---

src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.ts
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts

Adjusted the y-axis label to 'kW per half hour' and the chart title to reflect 'per half hour' data. Enhanced heatmap visualization by refining the color scale and adding z-smooth for better contour transitions.

Update chart labels and improve heatmap visualization

---

src/app/_services/db.service.ts
src/app/pages/reports/generate-report/generate-report.component.html
src/app/pages/reports/generate-report/generate-report.component.ts

Added 3 new tabs to reecommendations table.
1) Excess
2) Deficit
3) Solutions

Digital Twin recommendations (3 tabs added)

---

src/app/pages/envirotrack/import/supply/supply.component.html
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.ts

1. "asc" information and titles were swapped with "mic" information and titles
2. "asc" label on maximum demand chart swapped with "mic" label

157 mic graphs

---

src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.ts
src/app/pages/envirotrack/report/scope-chart/scope-chart.component.html

1. average chart - this.companies under this.ChartData - the [0] was removed and replaced with question mark
2. scope-chart grid col size was changed to "col" instead of col-6

158 daily energy consumption mpan

---

src/app/pages/dashboard/sidebar-menu/sidebar-menu.component.html
src/app/pages/envirotrack/report/envirotrack-report-avg/envirotrack-report-avg.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-bar-small/envirotrack-bar-small.component.ts
src/app/pages/envirotrack/report/envirotrack-report-bar/envirotrack-report-bar.component.ts
src/app/pages/envirotrack/report/envirotrack-report-base1/envirotrack-report-base1.component.ts
src/app/pages/envirotrack/report/envirotrack-report-demand/envirotrack-report-demand.component.ts
src/app/pages/envirotrack/report/envirotrack-report-heatmap/envirotrack-report-heatmap.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-report-pie.component.ts
src/app/pages/envirotrack/report/envirotrack-report-pie/envirotrack-small-pie-chart/envirotrack-small-pie-chart.component.ts
src/app/pages/envirotrack/report/envirotrack-report-scatter/envirotrack-report-scatter.component.ts

1. if() created in getData() to show that if the selectedMpan is under mpan[] we can select the different mpans
2. if not the system will select the first mpan from the mpan list when we are switching companies
3. if statements fixed for all charts
4. bar small chart - onSelectCompany() - other functions are called there such as - updateSelectedCompany, updateCompanyId,updateSelectedMpan, getData
5. Fuel Data menulink added to sidebar-menu component (burger menu)

162 changing company while on charts page

---

src/app/_services/db.service.ts
src/app/pages/reports/generate-report/generate-report.component.html
src/app/pages/reports/generate-report/generate-report.component.ts

Adding recommendations table updates to digital twin branch.

digital-twin-reco-table

---

src/app/pages/envirotrack/import/import-envirotrack/import-envirotrack.component.ts

1. adding comments to check where the issue is coming from
2. if data isValid - this.selectedMpan equals was removed
3. the if statement for displaying the mpan was modified so if there isn't customMpan the dragged mpan will be displayed

170 import hh data mpan

---

src/app/pages/digital-twins/dt-report/dt-report.component.html
src/app/pages/digital-twins/dt-report/dt-report.component.ts
src/app/pages/digital-twins/dt-report/mergeDuplicateSolutions.ts
src/app/pages/reports/generate-report/generate-report.component.html
src/app/pages/reports/generate-report/generate-report.component.ts
src/styles.scss

Adding digital twins to master. 
Fixed issues with duplicating cluster solutions.
Payback is now an average of all duplicates

156-digital-twins

---

src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.html
src/app/pages/envirotrack/import/data-capture-spreadsheet-fuels/data-capture-spreadsheet-fuels.component.ts
src/app/pages/reports/generate-report/generate-report.component.ts

1. style class was added to save btn on data-caoture-spreadsheet-fuels
2. calculateScopeTable- was populated with if statements to determine if the fuel type is hhd
3. conversionFactors object was populated with missing values or types
4. scope 1 and scope 2 were set in a if statement to show that electricity is scope 2
5. defaultConversionFactor was added if there is a custom type name
6. if() was added to sort the situation is we don't have selectedConversionFactor
7. fuel data - when the fuel type name is being changed a message with info is appearing

153 co2e units incorrect

---

src/app/pages/reports/generate-report/generate-report.component.html

editable was removed from margin dropdown

editable was removed from dropdown

---

src/app/_services/dt.service.ts
src/app/pages/digital-twins/dt-report/dt-report.component.ts
src/app/pages/digital-twins/dt-report/mergeDuplicateSolutions.ts

Data that is added to the PET tool in terms of energy should be pulled through to the digital twin consumption and costs.

174-fetching-hh-costing-from-pet-tool

---

src/app/_services/db.service.ts
src/app/app.routes.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/sidebar-menu/sidebar-menu.component.html
src/app/pages/files/files.component.html
src/app/pages/files/files.component.spec.ts
src/app/pages/files/files.component.ts

1. files added to dashboard  and sidemenu
2. files html file was set in a grid
3. `FilesComponent` to display and download files associated with companies
4. Created corresponding service methods and unit tests
5. Introduce a new `FilesComponent` to display

180 add file system
